### PR TITLE
Update Flacon to 7.0.0

### PR DESCRIPTION
**Pull request by Eonfge**
Also include library updates for some codecs

### CODE REVIEW

**Comment by SokoloffA** [comment]
I forgot to update com.github.Flacon.metainfo.xml 
I'll release 7.0.1 in a minute

**Comment by Eonfge** [comment]
O wow, that would be great. Thanks for your quick response. 

Honestly, I also often forget the metainfo.xml, so don't feel to bad

**Comment by SokoloffA** [comment]
Maybe we can automate this using the [github API](https://api.github.com/repos/flacon/flacon/releases)? Update metainfo on the fly?

**Comment by Eonfge** [comment]
Technically, that's certainly possible, but I have to warn you that setting up and maintaining such a pipeline might be overkill. I know a project or two who have a CMake command to append the latest release automatically, but that too is a surprising amount of work:

- First, you'll have to make sure that whenever you make a release, it runs a task
- Then it should add a release number and data for each tag on git
- Then it should force-push that change on the release tag, so that every release has the latest release notes

And... following that discussion up, what to do with the actual release notes? the metainfo.xml has room so that you can define all release notes. I normally don't bother doing it, but automating that too will quickly get quite fiddly with all the xml tags.

Honestly, don't worry to much about it for now. If all else fails, we can just add them later here :p

**Pull request merged**
